services:
  frontend:
    build: 
      context: ./frontend
      network: host
    container_name: frontend
    restart: no
    ports:
      - "3000:3000"
    networks:
      - webnet
    env_file: .env
    environment:
      - NODE_ENV=production
      - ORIGIN=http://localhost
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host

  backend:
    build: 
      context: ./backend
      network: host
    container_name: backend
    restart: no
    ports:
      - "8000:8000"
    env_file: .env
    #depends_on:
    #  - db
    networks:
      - webnet
    environment:
      - EXPIRATION_TIME=300   # timeout for login and cookies/jwt in seconds

  #db:
  #  image: postgres:16
  #  container_name: postgres
  #  restart: always
  #  volumes:
  #    - pgdata:/var/lib/postgresql/data
  #    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  #  environment:
  #    - POSTGRES_USER=${POSTGRES_USER}
  #    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #    - POSTGRES_DB=${POSTGRES_DB}
  #  networks:
  #    - webnet

  nginx:
    build: 
      context: ./nginx
      network: host
    container_name: nginx
    restart: no
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webnet

#volumes:
#  pgdata:

networks:
  webnet:
